before_script:
  - rustup update stable
  - rustup default stable

stable:cargo:
  # image: rustdocker/rust:stable
  # stage: test
  script:
    - make test
    - cargo build --release --bin restapi


