before_script:
  - rustup update stable
  - rustup default stable
  - diesel migration run
  - echo $DATABASE_URL

stable:cargo:
  # image: rustdocker/rust:stable
  # stage: test
  variables:
    DATABASE_URL: postgresql://postgres:123123@localhost/apf_test?sslmode=disable
    BUILD_FOR: nightly
  script:
    - make test
    - cargo build --release --bin restapi
    - cp target/release/restapi /home/gitlab-runner/releases/apf-server_build-`date +"%Y-%m-%d"`


