[package]
name = "apf-proc-macro"
version = "0.1.0"
authors = ["robin <robin@ansvia.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
syn = "0.15"
quote = "0.6"
lazy_static = "1.2"
serde = "1.0.10"
serde_derive = "1.0.64"
serde_json = "1.0.19"
# darling = "0.8.5"
